### ISSUE TITLE
failed to launch simulators - rake aborted

### ISSUE THREAD

**Issue by CurlyHeir** [plu/parallel_ios_tests#15]
When i runned `rake launch``
i got this error

```
Przemysaw-Wosko-MacBook-Pro:parallel_ios_tests kudlaty$ rake launch
The files /Applications/Xcode and /Users/kudlaty/parallel_ios_tests/2.app/Contents/Developer/Applications/Simulator.app do not exist.
The files /Applications/Xcode and /Users/kudlaty/parallel_ios_tests/2.app/Contents/Developer/Applications/Simulator.app do not exist.
/Users/kudlaty/parallel_ios_tests/xctool/xctool.sh -derivedDataPath '/Users/kudlaty/parallel_ios_tests/build' -scheme SampleApp -sdk iphonesimulator -workspace SampleApp.xcworkspace build
[Info] Loading settings for scheme 'SampleApp' ... (660 ms)

=== BUILD ===

  xcodebuild build SampleApp
    SampleApp / SampleApp (Debug)
      ✓ Check dependencies (113 ms)
      0 errored, 0 warning (117 ms)



** BUILD SUCCEEDED ** (716 ms)

rake aborted!
StandardError: An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
/Library/Ruby/Gems/2.0.0/gems/simctl-1.5.0/lib/simctl/executor.rb:14:in `block in execute'
/Library/Ruby/Gems/2.0.0/gems/simctl-1.5.0/lib/simctl/executor.rb:10:in `execute'
/Library/Ruby/Gems/2.0.0/gems/simctl-1.5.0/lib/simctl/command/install.rb:14:in `install_app'
/Library/Ruby/Gems/2.0.0/gems/simctl-1.5.0/lib/simctl.rb:22:in `method_missing'
/Library/Ruby/Gems/2.0.0/gems/simctl-1.5.0/lib/simctl/device.rb:53:in `install!'
/Users/kudlaty/parallel_ios_tests/Rakefile:91:in `block (2 levels) in <top (required)>'
/Users/kudlaty/parallel_ios_tests/Rakefile:90:in `each'
/Users/kudlaty/parallel_ios_tests/Rakefile:90:in `block in <top (required)>'
Tasks: TOP => launch
(See full trace by running task with --trace)
Przemysaw-Wosko-MacBook-Pro:parallel_ios_tests kudlaty$ rake launch
The files /Applications/Xcode and /Users/kudlaty/parallel_ios_tests/2.app/Contents/Developer/Applications/Simulator.app do not exist.
The files /Applications/Xcode and /Users/kudlaty/parallel_ios_tests/2.app/Contents/Developer/Applications/Simulator.app do not exist.
The files /Applications/Xcode and /Users/kudlaty/parallel_ios_tests/2.app/Contents/Developer/Applications/Simulator.app do not exist.
The files /Applications/Xcode and /Users/kudlaty/parallel_ios_tests/2.app/Contents/Developer/Applications/Simulator.app do not exist.
/Users/kudlaty/parallel_ios_tests/xctool/xctool.sh -derivedDataPath '/Users/kudlaty/parallel_ios_tests/build' -scheme SampleApp -sdk iphonesimulator -workspace SampleApp.xcworkspace build
[Info] Loading settings for scheme 'SampleApp' ... (785 ms)

=== BUILD ===

  xcodebuild build SampleApp
    SampleApp / SampleApp (Debug)
      ✓ Check dependencies (112 ms)
      0 errored, 0 warning (118 ms)



** BUILD SUCCEEDED ** (714 ms)

rake aborted!
StandardError: An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
/Library/Ruby/Gems/2.0.0/gems/simctl-1.5.0/lib/simctl/executor.rb:14:in `block in execute'
/Library/Ruby/Gems/2.0.0/gems/simctl-1.5.0/lib/simctl/executor.rb:10:in `execute'
/Library/Ruby/Gems/2.0.0/gems/simctl-1.5.0/lib/simctl/command/install.rb:14:in `install_app'
/Library/Ruby/Gems/2.0.0/gems/simctl-1.5.0/lib/simctl.rb:22:in `method_missing'
/Library/Ruby/Gems/2.0.0/gems/simctl-1.5.0/lib/simctl/device.rb:53:in `install!'
/Users/kudlaty/parallel_ios_tests/Rakefile:91:in `block (2 levels) in <top (required)>'
/Users/kudlaty/parallel_ios_tests/Rakefile:90:in `each'
/Users/kudlaty/parallel_ios_tests/Rakefile:90:in `block in <top (required)>'
Tasks: TOP => launch
(See full trace by running task with --trace)
Przemysaw-Wosko-MacBook-Pro:parallel_ios_tests kudlaty$ 
```

**Comment by plu** [comment]
`xctool` based solution is deprecated, closing this issue because of that fact.
